-- ============================================================
-- Migration 027: Antwort-Datenbank statt Pflicht-Abstimmung für jede Antwort
-- ============================================================
-- Bisher musste JEDE Antwort per Mehrheitsvotum von den Mitspielern
-- bestätigt werden (Topic-Mechanik B) -- das bremst das Spiel aus und
-- ist bei bekannten, klar richtigen Antworten unnötig ("Eiche" bei
-- "Bäume" braucht keine Abstimmung). Jetzt gibt es pro Kategorie eine
-- Referenzliste bekannter Antworten (topic_answers): trifft die
-- eingereichte Antwort (case-insensitive) einen Eintrag, wird sie
-- SOFORT automatisch angenommen -- keine Wartezeit, kein Voting.
--
-- Antworten, die NICHT in der Liste stehen, fallen weiterhin auf das
-- bestehende Mehrheits-Voting zurück (Migration 001/018) -- das bleibt
-- die Auffang-Lösung für kreative, aber gültige Antworten, die (noch)
-- nicht in der Referenzliste stehen. Die Liste wächst mit jeder neuen
-- Kategorie/Erweiterung, ersetzt das Voting aber nicht komplett.
--
-- Seed: ~1100 Antworten über alle 54 bestehenden Kategorien (siehe
-- gen_topic_answers.py im Repo-Root), portiert aus den bisherigen
-- Bot-Antwortlisten (botAnswers.ts) und für "Bäume" (Nutzer-Beispiel)
-- deutlich auf ~50 bekannte Baumarten erweitert.
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.topic_answers (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    topic_pool_id  UUID NOT NULL REFERENCES public.topic_pool(id) ON DELETE CASCADE,
    answer         TEXT NOT NULL,
    lower_answer   TEXT GENERATED ALWAYS AS (lower(answer)) STORED,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (topic_pool_id, lower_answer)
);

CREATE INDEX IF NOT EXISTS idx_topic_answers_topic ON public.topic_answers (topic_pool_id);

ALTER TABLE public.topic_answers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "topic_answers_read_all" ON public.topic_answers;
CREATE POLICY "topic_answers_read_all" ON public.topic_answers FOR SELECT USING (TRUE);


CREATE OR REPLACE FUNCTION public.rpc_attempt_pass(
    p_code TEXT, p_player_id UUID, p_answer TEXT
) RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
declare
  v_lobby public.lobbies%ROWTYPE;
  v_attempt uuid;
  v_clean text;
  v_topic text;
  v_known boolean;
begin
  select * into v_lobby from public.lobbies where code = upper(p_code) for update;
  if not found then raise exception 'lobby_not_found'; end if;

  if not public._verify_session(v_lobby.id, p_player_id) then
    raise exception 'invalid_session';
  end if;

  if v_lobby.phase <> 'running' then raise exception 'lobby_not_running'; end if;
  if v_lobby.holder_player_id <> p_player_id then raise exception 'not_holder'; end if;
  if v_lobby.current_attempt_id is not null then raise exception 'attempt_already_open'; end if;

  v_clean := trim(p_answer);
  if length(v_clean) = 0 then raise exception 'empty_answer'; end if;
  if length(v_clean) > 60 then raise exception 'answer_too_long'; end if;

  if exists (
    select 1 from unnest(v_lobby.used_answers) as used
    where lower(used) = lower(v_clean)
  ) then raise exception 'answer_already_used'; end if;

  v_topic := coalesce(v_lobby.topic_selected, v_lobby.topic, '');

  insert into public.pass_attempts (lobby_id, round_number, holder_player_id, answer, topic)
    values (v_lobby.id, coalesce(v_lobby.round_number, 0), p_player_id, v_clean, v_topic)
    returning id into v_attempt;

  update public.lobbies set current_attempt_id = v_attempt where id = v_lobby.id;

  -- Antwort-Datenbank: bekannte, korrekte Antwort -> sofort annehmen,
  -- kein Voting nötig. _finalize_attempt_accept setzt current_attempt_id
  -- selbst wieder auf null und stößt rpc_pass_potato an.
  select exists (
    select 1
    from public.topic_answers ta
    join public.topic_pool tp on tp.id = ta.topic_pool_id
    where lower(tp.text) = lower(v_topic)
      and ta.lower_answer = lower(v_clean)
  ) into v_known;

  if v_known then
    perform public._finalize_attempt_accept(v_attempt);
  end if;

  return v_attempt;
end;
$function$;

COMMIT;

BEGIN;

-- Auto-generiert aus botAnswers.ts + Erweiterungen, siehe gen_topic_answers.py im Repo-Root (kann geloescht werden)
INSERT INTO public.topic_answers (topic_pool_id, answer)
SELECT tp.id, v.answer
FROM public.topic_pool tp
JOIN (VALUES
    ('Automarken', 'BMW'),
    ('Automarken', 'Audi'),
    ('Automarken', 'Mercedes'),
    ('Automarken', 'VW'),
    ('Automarken', 'Porsche'),
    ('Automarken', 'Ferrari'),
    ('Automarken', 'Toyota'),
    ('Automarken', 'Ford'),
    ('Automarken', 'Opel'),
    ('Automarken', 'Honda'),
    ('Automarken', 'Tesla'),
    ('Automarken', 'Mazda'),
    ('Automarken', 'Nissan'),
    ('Automarken', 'Hyundai'),
    ('Automarken', 'Kia'),
    ('Automarken', 'Skoda'),
    ('Automarken', 'Seat'),
    ('Automarken', 'Renault'),
    ('Automarken', 'Peugeot'),
    ('Automarken', 'Citroen'),
    ('Automarken', 'Fiat'),
    ('Automarken', 'Volvo'),
    ('Automarken', 'Jaguar'),
    ('Automarken', 'Land Rover'),
    ('Automarken', 'Mini'),
    ('Automarken', 'Bentley'),
    ('Automarken', 'Rolls-Royce'),
    ('Automarken', 'Lamborghini'),
    ('Automarken', 'Maserati'),
    ('Automarken', 'Alfa Romeo'),
    ('Automarken', 'Subaru'),
    ('Automarken', 'Mitsubishi'),
    ('Automarken', 'Suzuki'),
    ('Automarken', 'Dacia'),
    ('Automarken', 'Chevrolet'),
    ('Automarken', 'Jeep'),
    ('Automarken', 'Chrysler'),
    ('Automarken', 'Cadillac'),
    ('Automarken', 'Lexus'),
    ('Automarken', 'Infiniti'),
    ('Automarken', 'Bugatti'),
    ('Automarken', 'Aston Martin'),
    ('Automarken', 'McLaren'),
    ('Automarken', 'Smart'),
    ('Tiere in Afrika', 'Löwe'),
    ('Tiere in Afrika', 'Elefant'),
    ('Tiere in Afrika', 'Giraffe'),
    ('Tiere in Afrika', 'Zebra'),
    ('Tiere in Afrika', 'Nashorn'),
    ('Tiere in Afrika', 'Gepard'),
    ('Tiere in Afrika', 'Hyäne'),
    ('Tiere in Afrika', 'Flusspferd'),
    ('Tiere in Afrika', 'Krokodil'),
    ('Tiere in Afrika', 'Affe'),
    ('Tiere in Afrika', 'Strauß'),
    ('Tiere in Afrika', 'Antilope'),
    ('Tiere in Afrika', 'Leopard'),
    ('Tiere in Afrika', 'Büffel'),
    ('Tiere in Afrika', 'Warzenschwein'),
    ('Tiere in Afrika', 'Gnu'),
    ('Tiere in Afrika', 'Springbock'),
    ('Tiere in Afrika', 'Schakal'),
    ('Tiere in Afrika', 'Manguste'),
    ('Tiere in Afrika', 'Pavian'),
    ('Tiere in Afrika', 'Impala'),
    ('Tiere in Afrika', 'Kudu'),
    ('Tiere in Afrika', 'Wildhund'),
    ('Tiere in Afrika', 'Erdmännchen'),
    ('Haustiere', 'Hund'),
    ('Haustiere', 'Katze'),
    ('Haustiere', 'Hamster'),
    ('Haustiere', 'Meerschweinchen'),
    ('Haustiere', 'Kaninchen'),
    ('Haustiere', 'Wellensittich'),
    ('Haustiere', 'Goldfisch'),
    ('Haustiere', 'Schildkröte'),
    ('Haustiere', 'Papagei'),
    ('Haustiere', 'Frettchen'),
    ('Haustiere', 'Chinchilla'),
    ('Haustiere', 'Ratte'),
    ('Haustiere', 'Maus'),
    ('Haustiere', 'Degu'),
    ('Haustiere', 'Kanarienvogel'),
    ('Haustiere', 'Nymphensittich'),
    ('Haustiere', 'Zwerghamster'),
    ('Haustiere', 'Gecko'),
    ('Haustiere', 'Schlange'),
    ('Fußball-Vereine', 'Bayern München'),
    ('Fußball-Vereine', 'Dortmund'),
    ('Fußball-Vereine', 'Schalke'),
    ('Fußball-Vereine', 'Real Madrid'),
    ('Fußball-Vereine', 'Barcelona'),
    ('Fußball-Vereine', 'Manchester United'),
    ('Fußball-Vereine', 'Liverpool'),
    ('Fußball-Vereine', 'Arsenal'),
    ('Fußball-Vereine', 'PSG'),
    ('Fußball-Vereine', 'Juventus'),
    ('Fußball-Vereine', 'Inter'),
    ('Fußball-Vereine', 'Köln'),
    ('Fußball-Vereine', 'Bayer Leverkusen'),
    ('Fußball-Vereine', 'RB Leipzig'),
    ('Fußball-Vereine', 'Eintracht Frankfurt'),
    ('Fußball-Vereine', 'Werder Bremen'),
    ('Fußball-Vereine', 'Hamburger SV'),
    ('Fußball-Vereine', 'Hertha BSC'),
    ('Fußball-Vereine', 'VfB Stuttgart'),
    ('Fußball-Vereine', 'Manchester City'),
    ('Fußball-Vereine', 'Chelsea'),
    ('Fußball-Vereine', 'Tottenham'),
    ('Fußball-Vereine', 'AC Milan'),
    ('Fußball-Vereine', 'Atletico Madrid'),
    ('Fußball-Vereine', 'Ajax'),
    ('Fußball-Vereine', 'Benfica'),
    ('Fußball-Vereine', 'Porto'),
    ('Länder in Europa', 'Deutschland'),
    ('Länder in Europa', 'Frankreich'),
    ('Länder in Europa', 'Italien'),
    ('Länder in Europa', 'Spanien'),
    ('Länder in Europa', 'Portugal'),
    ('Länder in Europa', 'Österreich'),
    ('Länder in Europa', 'Schweiz'),
    ('Länder in Europa', 'Polen'),
    ('Länder in Europa', 'Niederlande'),
    ('Länder in Europa', 'Belgien'),
    ('Länder in Europa', 'Schweden'),
    ('Länder in Europa', 'Norwegen'),
    ('Länder in Europa', 'Dänemark'),
    ('Länder in Europa', 'Finnland'),
    ('Länder in Europa', 'Griechenland'),
    ('Länder in Europa', 'Irland'),
    ('Länder in Europa', 'Island'),
    ('Länder in Europa', 'Kroatien'),
    ('Länder in Europa', 'Serbien'),
    ('Länder in Europa', 'Ungarn'),
    ('Länder in Europa', 'Tschechien'),
    ('Länder in Europa', 'Slowakei'),
    ('Länder in Europa', 'Slowenien'),
    ('Länder in Europa', 'Rumänien'),
    ('Länder in Europa', 'Bulgarien'),
    ('Länder in Europa', 'Litauen'),
    ('Länder in Europa', 'Lettland'),
    ('Länder in Europa', 'Estland'),
    ('Länder in Europa', 'Luxemburg'),
    ('Länder in Europa', 'Malta'),
    ('Länder in Europa', 'Zypern'),
    ('Länder in Europa', 'Albanien'),
    ('Länder in Europa', 'Montenegro'),
    ('Länder in Europa', 'Bosnien'),
    ('Länder in Europa', 'Nordmazedonien'),
    ('Länder in Europa', 'Moldau'),
    ('Länder in Europa', 'Ukraine'),
    ('Länder in Europa', 'Weißrussland'),
    ('Länder in Europa', 'Russland'),
    ('Länder in Europa', 'Türkei'),
    ('Länder in Europa', 'Monaco'),
    ('Länder in Europa', 'Liechtenstein'),
    ('Länder in Europa', 'Andorra'),
    ('Länder in Europa', 'San Marino'),
    ('Länder in Europa', 'Vatikanstadt'),
    ('Länder in Europa', 'Kosovo'),
    ('Länder in Europa', 'Großbritannien'),
    ('Hauptstädte', 'Berlin'),
    ('Hauptstädte', 'Paris'),
    ('Hauptstädte', 'Madrid'),
    ('Hauptstädte', 'Rom'),
    ('Hauptstädte', 'Wien'),
    ('Hauptstädte', 'Bern'),
    ('Hauptstädte', 'Warschau'),
    ('Hauptstädte', 'Amsterdam'),
    ('Hauptstädte', 'Brüssel'),
    ('Hauptstädte', 'Stockholm'),
    ('Hauptstädte', 'Oslo'),
    ('Hauptstädte', 'London'),
    ('Hauptstädte', 'Kopenhagen'),
    ('Hauptstädte', 'Helsinki'),
    ('Hauptstädte', 'Athen'),
    ('Hauptstädte', 'Dublin'),
    ('Hauptstädte', 'Reykjavik'),
    ('Hauptstädte', 'Zagreb'),
    ('Hauptstädte', 'Belgrad'),
    ('Hauptstädte', 'Budapest'),
    ('Hauptstädte', 'Prag'),
    ('Hauptstädte', 'Bratislava'),
    ('Hauptstädte', 'Ljubljana'),
    ('Hauptstädte', 'Bukarest'),
    ('Hauptstädte', 'Sofia'),
    ('Hauptstädte', 'Vilnius'),
    ('Hauptstädte', 'Riga'),
    ('Hauptstädte', 'Tallinn'),
    ('Hauptstädte', 'Luxemburg'),
    ('Hauptstädte', 'Valletta'),
    ('Hauptstädte', 'Nikosia'),
    ('Hauptstädte', 'Tirana'),
    ('Hauptstädte', 'Podgorica'),
    ('Hauptstädte', 'Sarajevo'),
    ('Hauptstädte', 'Skopje'),
    ('Hauptstädte', 'Chisinau'),
    ('Hauptstädte', 'Kiew'),
    ('Hauptstädte', 'Minsk'),
    ('Hauptstädte', 'Moskau'),
    ('Hauptstädte', 'Ankara'),
    ('Obst', 'Apfel'),
    ('Obst', 'Birne'),
    ('Obst', 'Banane'),
    ('Obst', 'Orange'),
    ('Obst', 'Erdbeere'),
    ('Obst', 'Kirsche'),
    ('Obst', 'Pfirsich'),
    ('Obst', 'Mango'),
    ('Obst', 'Ananas'),
    ('Obst', 'Traube'),
    ('Obst', 'Wassermelone'),
    ('Obst', 'Kiwi'),
    ('Obst', 'Zitrone'),
    ('Obst', 'Limette'),
    ('Obst', 'Grapefruit'),
    ('Obst', 'Mandarine'),
    ('Obst', 'Pflaume'),
    ('Obst', 'Aprikose'),
    ('Obst', 'Feige'),
    ('Obst', 'Granatapfel'),
    ('Obst', 'Papaya'),
    ('Obst', 'Litschi'),
    ('Obst', 'Physalis'),
    ('Obst', 'Heidelbeere'),
    ('Obst', 'Himbeere'),
    ('Obst', 'Brombeere'),
    ('Obst', 'Johannisbeere'),
    ('Obst', 'Stachelbeere'),
    ('Obst', 'Quitte'),
    ('Obst', 'Nektarine'),
    ('Obst', 'Maracuja'),
    ('Obst', 'Guave'),
    ('Obst', 'Dattel'),
    ('Obst', 'Kaki'),
    ('Gemüse', 'Karotte'),
    ('Gemüse', 'Tomate'),
    ('Gemüse', 'Gurke'),
    ('Gemüse', 'Salat'),
    ('Gemüse', 'Paprika'),
    ('Gemüse', 'Brokkoli'),
    ('Gemüse', 'Spinat'),
    ('Gemüse', 'Zwiebel'),
    ('Gemüse', 'Kartoffel'),
    ('Gemüse', 'Aubergine'),
    ('Gemüse', 'Zucchini'),
    ('Gemüse', 'Kohl'),
    ('Gemüse', 'Blumenkohl'),
    ('Gemüse', 'Rosenkohl'),
    ('Gemüse', 'Lauch'),
    ('Gemüse', 'Sellerie'),
    ('Gemüse', 'Radieschen'),
    ('Gemüse', 'Rote Bete'),
    ('Gemüse', 'Kürbis'),
    ('Gemüse', 'Mais'),
    ('Gemüse', 'Erbsen'),
    ('Gemüse', 'Bohnen'),
    ('Gemüse', 'Fenchel'),
    ('Gemüse', 'Rettich'),
    ('Gemüse', 'Spargel'),
    ('Farben', 'Rot'),
    ('Farben', 'Blau'),
    ('Farben', 'Grün'),
    ('Farben', 'Gelb'),
    ('Farben', 'Schwarz'),
    ('Farben', 'Weiß'),
    ('Farben', 'Orange'),
    ('Farben', 'Lila'),
    ('Farben', 'Rosa'),
    ('Farben', 'Braun'),
    ('Farben', 'Grau'),
    ('Farben', 'Türkis'),
    ('Farben', 'Violett'),
    ('Farben', 'Pink'),
    ('Farben', 'Beige'),
    ('Farben', 'Gold'),
    ('Farben', 'Silber'),
    ('Farben', 'Bronze'),
    ('Farben', 'Magenta'),
    ('Farben', 'Cyan'),
    ('Farben', 'Lindgrün'),
    ('Farben', 'Bordeaux'),
    ('Farben', 'Petrol'),
    ('Farben', 'Khaki'),
    ('Filme', 'Inception'),
    ('Filme', 'Titanic'),
    ('Filme', 'Avatar'),
    ('Filme', 'Matrix'),
    ('Filme', 'Joker'),
    ('Filme', 'Gladiator'),
    ('Filme', 'Interstellar'),
    ('Filme', 'Forrest Gump'),
    ('Filme', 'Pulp Fiction'),
    ('Filme', 'Sieben'),
    ('Filme', 'Der Pate'),
    ('Filme', 'Fight Club'),
    ('Filme', 'Herr der Ringe'),
    ('Filme', 'Star Wars'),
    ('Filme', 'Jurassic Park'),
    ('Filme', 'Die Verurteilten'),
    ('Filme', 'Schindlers Liste'),
    ('Filme', 'Die Dunkle Ritter'),
    ('Filme', 'Fluch der Karibik'),
    ('Filme', 'Harry Potter'),
    ('Serien', 'Breaking Bad'),
    ('Serien', 'Game of Thrones'),
    ('Serien', 'Friends'),
    ('Serien', 'Stranger Things'),
    ('Serien', 'The Office'),
    ('Serien', 'Lost'),
    ('Serien', 'Money Heist'),
    ('Serien', 'Dark'),
    ('Serien', 'Witcher'),
    ('Serien', 'Vikings'),
    ('Serien', 'Better Call Saul'),
    ('Serien', 'The Crown'),
    ('Serien', 'Suits'),
    ('Serien', 'Peaky Blinders'),
    ('Serien', 'How I Met Your Mother'),
    ('Serien', 'The Big Bang Theory'),
    ('Serien', 'Narcos'),
    ('Serien', 'Sherlock'),
    ('Musiker/Bands', 'Coldplay'),
    ('Musiker/Bands', 'Beatles'),
    ('Musiker/Bands', 'Queen'),
    ('Musiker/Bands', 'Eminem'),
    ('Musiker/Bands', 'Drake'),
    ('Musiker/Bands', 'Adele'),
    ('Musiker/Bands', 'Ed Sheeran'),
    ('Musiker/Bands', 'Rammstein'),
    ('Musiker/Bands', 'Metallica'),
    ('Musiker/Bands', 'AC/DC'),
    ('Musiker/Bands', 'Linkin Park'),
    ('Musiker/Bands', 'Nirvana'),
    ('Musiker/Bands', 'Pink Floyd'),
    ('Musiker/Bands', 'Rolling Stones'),
    ('Musiker/Bands', 'U2'),
    ('Musiker/Bands', 'Guns N'' Roses'),
    ('Musiker/Bands', 'Red Hot Chili Peppers'),
    ('Musiker/Bands', 'Green Day'),
    ('Musiker/Bands', 'Foo Fighters'),
    ('Musiker/Bands', 'Muse'),
    ('Schauspieler', 'Tom Hanks'),
    ('Schauspieler', 'Brad Pitt'),
    ('Schauspieler', 'Leonardo DiCaprio'),
    ('Schauspieler', 'Will Smith'),
    ('Schauspieler', 'Morgan Freeman'),
    ('Schauspieler', 'Denzel Washington'),
    ('Schauspieler', 'Robert De Niro'),
    ('Schauspieler', 'Al Pacino'),
    ('Schauspieler', 'Johnny Depp'),
    ('Schauspieler', 'Tom Cruise'),
    ('Schauspieler', 'Matt Damon'),
    ('Schauspieler', 'Christian Bale'),
    ('Schauspieler', 'Ryan Gosling'),
    ('Schauspieler', 'Scarlett Johansson'),
    ('Schauspieler', 'Angelina Jolie'),
    ('Schauspieler', 'Meryl Streep'),
    ('Berufe', 'Arzt'),
    ('Berufe', 'Lehrer'),
    ('Berufe', 'Anwalt'),
    ('Berufe', 'Ingenieur'),
    ('Berufe', 'Bäcker'),
    ('Berufe', 'Koch'),
    ('Berufe', 'Polizist'),
    ('Berufe', 'Feuerwehrmann'),
    ('Berufe', 'Pilot'),
    ('Berufe', 'Friseur'),
    ('Berufe', 'Mechaniker'),
    ('Berufe', 'Krankenschwester'),
    ('Berufe', 'Elektriker'),
    ('Berufe', 'Klempner'),
    ('Berufe', 'Architekt'),
    ('Berufe', 'Journalist'),
    ('Berufe', 'Programmierer'),
    ('Berufe', 'Buchhalter'),
    ('Berufe', 'Verkäufer'),
    ('Berufe', 'Gärtner'),
    ('Körperteile', 'Knie'),
    ('Körperteile', 'Arm'),
    ('Körperteile', 'Bein'),
    ('Körperteile', 'Hand'),
    ('Körperteile', 'Fuß'),
    ('Körperteile', 'Kopf'),
    ('Körperteile', 'Nase'),
    ('Körperteile', 'Auge'),
    ('Körperteile', 'Ohr'),
    ('Körperteile', 'Mund'),
    ('Körperteile', 'Finger'),
    ('Körperteile', 'Ellenbogen'),
    ('Körperteile', 'Schulter'),
    ('Körperteile', 'Rücken'),
    ('Körperteile', 'Bauch'),
    ('Körperteile', 'Hüfte'),
    ('Körperteile', 'Knöchel'),
    ('Körperteile', 'Zehe'),
    ('Körperteile', 'Kinn'),
    ('Körperteile', 'Stirn'),
    ('Körperteile', 'Wange'),
    ('Körperteile', 'Hals'),
    ('Körperteile', 'Handgelenk'),
    ('Dinge in der Küche', 'Messer'),
    ('Dinge in der Küche', 'Gabel'),
    ('Dinge in der Küche', 'Löffel'),
    ('Dinge in der Küche', 'Teller'),
    ('Dinge in der Küche', 'Topf'),
    ('Dinge in der Küche', 'Pfanne'),
    ('Dinge in der Küche', 'Herd'),
    ('Dinge in der Küche', 'Kühlschrank'),
    ('Dinge in der Küche', 'Mikrowelle'),
    ('Dinge in der Küche', 'Tasse'),
    ('Dinge in der Küche', 'Glas'),
    ('Dinge in der Küche', 'Schneidebrett'),
    ('Dinge in der Küche', 'Sieb'),
    ('Dinge in der Küche', 'Schüssel'),
    ('Dinge in der Küche', 'Backofen'),
    ('Dinge in der Küche', 'Toaster'),
    ('Dinge in der Küche', 'Wasserkocher'),
    ('Dinge in der Küche', 'Reibe'),
    ('Dinge in der Küche', 'Schöpfkelle'),
    ('Dinge in der Küche', 'Spülmaschine'),
    ('Dinge im Supermarkt', 'Brot'),
    ('Dinge im Supermarkt', 'Milch'),
    ('Dinge im Supermarkt', 'Käse'),
    ('Dinge im Supermarkt', 'Butter'),
    ('Dinge im Supermarkt', 'Joghurt'),
    ('Dinge im Supermarkt', 'Eier'),
    ('Dinge im Supermarkt', 'Reis'),
    ('Dinge im Supermarkt', 'Nudeln'),
    ('Dinge im Supermarkt', 'Mehl'),
    ('Dinge im Supermarkt', 'Zucker'),
    ('Dinge im Supermarkt', 'Salz'),
    ('Dinge im Supermarkt', 'Öl'),
    ('Dinge im Supermarkt', 'Kaffee'),
    ('Dinge im Supermarkt', 'Tee'),
    ('Dinge im Supermarkt', 'Gemüse'),
    ('Dinge im Supermarkt', 'Obst'),
    ('Dinge im Supermarkt', 'Fleisch'),
    ('Dinge im Supermarkt', 'Fisch'),
    ('Dinge im Supermarkt', 'Konserven'),
    ('Dinge im Supermarkt', 'Süßigkeiten'),
    ('Dinge im Supermarkt', 'Tiefkühlkost'),
    ('Dinge im Supermarkt', 'Waschmittel'),
    ('Getränke', 'Cola'),
    ('Getränke', 'Wasser'),
    ('Getränke', 'Saft'),
    ('Getränke', 'Tee'),
    ('Getränke', 'Kaffee'),
    ('Getränke', 'Limonade'),
    ('Getränke', 'Eistee'),
    ('Getränke', 'Smoothie'),
    ('Getränke', 'Milch'),
    ('Getränke', 'Bier'),
    ('Getränke', 'Wein'),
    ('Getränke', 'Sekt'),
    ('Getränke', 'Whisky'),
    ('Getränke', 'Wodka'),
    ('Getränke', 'Rum'),
    ('Getränke', 'Gin'),
    ('Getränke', 'Energy Drink'),
    ('Getränke', 'Mineralwasser'),
    ('Getränke', 'Kakao'),
    ('Getränke', 'Buttermilch'),
    ('Alkoholische Getränke', 'Bier'),
    ('Alkoholische Getränke', 'Wein'),
    ('Alkoholische Getränke', 'Wodka'),
    ('Alkoholische Getränke', 'Whisky'),
    ('Alkoholische Getränke', 'Rum'),
    ('Alkoholische Getränke', 'Gin'),
    ('Alkoholische Getränke', 'Tequila'),
    ('Alkoholische Getränke', 'Sekt'),
    ('Alkoholische Getränke', 'Schnaps'),
    ('Alkoholische Getränke', 'Likör'),
    ('Alkoholische Getränke', 'Cocktail'),
    ('Alkoholische Getränke', 'Cognac'),
    ('Alkoholische Getränke', 'Brandy'),
    ('Alkoholische Getränke', 'Grappa'),
    ('Alkoholische Getränke', 'Absinth'),
    ('Alkoholische Getränke', 'Aperol'),
    ('Alkoholische Getränke', 'Prosecco'),
    ('Alkoholische Getränke', 'Jägermeister'),
    ('Alkoholische Getränke', 'Baileys'),
    ('Fast Food', 'Pizza'),
    ('Fast Food', 'Burger'),
    ('Fast Food', 'Pommes'),
    ('Fast Food', 'Döner'),
    ('Fast Food', 'Hotdog'),
    ('Fast Food', 'Sandwich'),
    ('Fast Food', 'Wrap'),
    ('Fast Food', 'Nuggets'),
    ('Fast Food', 'Salat'),
    ('Fast Food', 'Sushi'),
    ('Fast Food', 'Kebab'),
    ('Fast Food', 'Currywurst'),
    ('Fast Food', 'Falafel'),
    ('Fast Food', 'Burrito'),
    ('Fast Food', 'Taco'),
    ('Fast Food', 'Nachos'),
    ('Fast Food', 'Chicken Wings'),
    ('Schulfächer', 'Mathe'),
    ('Schulfächer', 'Deutsch'),
    ('Schulfächer', 'Englisch'),
    ('Schulfächer', 'Geschichte'),
    ('Schulfächer', 'Geographie'),
    ('Schulfächer', 'Biologie'),
    ('Schulfächer', 'Chemie'),
    ('Schulfächer', 'Physik'),
    ('Schulfächer', 'Sport'),
    ('Schulfächer', 'Kunst'),
    ('Schulfächer', 'Musik'),
    ('Schulfächer', 'Religion'),
    ('Schulfächer', 'Ethik'),
    ('Schulfächer', 'Informatik'),
    ('Schulfächer', 'Französisch'),
    ('Schulfächer', 'Spanisch'),
    ('Schulfächer', 'Latein'),
    ('Schulfächer', 'Politik'),
    ('Schulfächer', 'Sozialkunde'),
    ('Schulfächer', 'Wirtschaft'),
    ('Sportarten', 'Tennis'),
    ('Sportarten', 'Fußball'),
    ('Sportarten', 'Basketball'),
    ('Sportarten', 'Volleyball'),
    ('Sportarten', 'Schwimmen'),
    ('Sportarten', 'Boxen'),
    ('Sportarten', 'Golf'),
    ('Sportarten', 'Schach'),
    ('Sportarten', 'Skifahren'),
    ('Sportarten', 'Surfen'),
    ('Sportarten', 'Klettern'),
    ('Sportarten', 'Handball'),
    ('Sportarten', 'Leichtathletik'),
    ('Sportarten', 'Turnen'),
    ('Sportarten', 'Radfahren'),
    ('Sportarten', 'Judo'),
    ('Sportarten', 'Karate'),
    ('Sportarten', 'Eishockey'),
    ('Sportarten', 'Rudern'),
    ('Sportarten', 'Reiten'),
    ('Sportarten', 'Segeln'),
    ('Musikinstrumente', 'Gitarre'),
    ('Musikinstrumente', 'Klavier'),
    ('Musikinstrumente', 'Geige'),
    ('Musikinstrumente', 'Trommel'),
    ('Musikinstrumente', 'Flöte'),
    ('Musikinstrumente', 'Saxophon'),
    ('Musikinstrumente', 'Trompete'),
    ('Musikinstrumente', 'Bass'),
    ('Musikinstrumente', 'Cello'),
    ('Musikinstrumente', 'Harmonika'),
    ('Musikinstrumente', 'Klarinette'),
    ('Musikinstrumente', 'Posaune'),
    ('Musikinstrumente', 'Harfe'),
    ('Musikinstrumente', 'Ukulele'),
    ('Musikinstrumente', 'Akkordeon'),
    ('Musikinstrumente', 'Orgel'),
    ('Musikinstrumente', 'Schlagzeug'),
    ('Musikinstrumente', 'Tuba'),
    ('Musikinstrumente', 'Oboe'),
    ('Bundesländer', 'Bayern'),
    ('Bundesländer', 'Berlin'),
    ('Bundesländer', 'Hamburg'),
    ('Bundesländer', 'Hessen'),
    ('Bundesländer', 'Sachsen'),
    ('Bundesländer', 'Thüringen'),
    ('Bundesländer', 'Bremen'),
    ('Bundesländer', 'Saarland'),
    ('Bundesländer', 'Brandenburg'),
    ('Bundesländer', 'Schleswig-Holstein'),
    ('Bundesländer', 'Niedersachsen'),
    ('Bundesländer', 'Baden-Württemberg'),
    ('Bundesländer', 'Nordrhein-Westfalen'),
    ('Bundesländer', 'Rheinland-Pfalz'),
    ('Bundesländer', 'Mecklenburg-Vorpommern'),
    ('Bundesländer', 'Sachsen-Anhalt'),
    ('Deutsche Städte', 'Hamburg'),
    ('Deutsche Städte', 'München'),
    ('Deutsche Städte', 'Köln'),
    ('Deutsche Städte', 'Frankfurt'),
    ('Deutsche Städte', 'Stuttgart'),
    ('Deutsche Städte', 'Düsseldorf'),
    ('Deutsche Städte', 'Leipzig'),
    ('Deutsche Städte', 'Dortmund'),
    ('Deutsche Städte', 'Essen'),
    ('Deutsche Städte', 'Bremen'),
    ('Deutsche Städte', 'Hannover'),
    ('Deutsche Städte', 'Nürnberg'),
    ('Deutsche Städte', 'Duisburg'),
    ('Deutsche Städte', 'Bochum'),
    ('Deutsche Städte', 'Wuppertal'),
    ('Deutsche Städte', 'Bielefeld'),
    ('Deutsche Städte', 'Bonn'),
    ('Deutsche Städte', 'Mannheim'),
    ('Deutsche Städte', 'Karlsruhe'),
    ('Deutsche Städte', 'Wiesbaden'),
    ('Deutsche Städte', 'Münster'),
    ('Deutsche Städte', 'Augsburg'),
    ('Deutsche Städte', 'Kiel'),
    ('Deutsche Städte', 'Dresden'),
    ('Großstädte weltweit', 'Tokio'),
    ('Großstädte weltweit', 'New York'),
    ('Großstädte weltweit', 'London'),
    ('Großstädte weltweit', 'Paris'),
    ('Großstädte weltweit', 'Istanbul'),
    ('Großstädte weltweit', 'Moskau'),
    ('Großstädte weltweit', 'Dubai'),
    ('Großstädte weltweit', 'Sydney'),
    ('Großstädte weltweit', 'Rio'),
    ('Großstädte weltweit', 'Kairo'),
    ('Großstädte weltweit', 'Bangkok'),
    ('Großstädte weltweit', 'Mumbai'),
    ('Großstädte weltweit', 'Los Angeles'),
    ('Großstädte weltweit', 'Chicago'),
    ('Großstädte weltweit', 'Toronto'),
    ('Großstädte weltweit', 'Mexiko-Stadt'),
    ('Großstädte weltweit', 'Sao Paulo'),
    ('Großstädte weltweit', 'Buenos Aires'),
    ('Großstädte weltweit', 'Shanghai'),
    ('Großstädte weltweit', 'Peking'),
    ('Großstädte weltweit', 'Seoul'),
    ('Großstädte weltweit', 'Singapur'),
    ('Großstädte weltweit', 'Hongkong'),
    ('Flüsse', 'Rhein'),
    ('Flüsse', 'Elbe'),
    ('Flüsse', 'Donau'),
    ('Flüsse', 'Main'),
    ('Flüsse', 'Mosel'),
    ('Flüsse', 'Nil'),
    ('Flüsse', 'Amazonas'),
    ('Flüsse', 'Mississippi'),
    ('Flüsse', 'Themse'),
    ('Flüsse', 'Seine'),
    ('Flüsse', 'Weser'),
    ('Flüsse', 'Oder'),
    ('Flüsse', 'Spree'),
    ('Flüsse', 'Neckar'),
    ('Flüsse', 'Isar'),
    ('Flüsse', 'Po'),
    ('Flüsse', 'Rhone'),
    ('Flüsse', 'Wolga'),
    ('Flüsse', 'Jangtse'),
    ('Flüsse', 'Ganges'),
    ('Berge', 'Mount Everest'),
    ('Berge', 'K2'),
    ('Berge', 'Matterhorn'),
    ('Berge', 'Zugspitze'),
    ('Berge', 'Brocken'),
    ('Berge', 'Kilimanjaro'),
    ('Berge', 'Mont Blanc'),
    ('Berge', 'Eiger'),
    ('Berge', 'Watzmann'),
    ('Berge', 'Großglockner'),
    ('Berge', 'Vesuv'),
    ('Berge', 'Ätna'),
    ('Berge', 'Feldberg'),
    ('Berge', 'Wank'),
    ('Berge', 'Nanga Parbat'),
    ('Berge', 'Annapurna'),
    ('Berge', 'Elbrus'),
    ('Meere und Ozeane', 'Atlantik'),
    ('Meere und Ozeane', 'Pazifik'),
    ('Meere und Ozeane', 'Mittelmeer'),
    ('Meere und Ozeane', 'Nordsee'),
    ('Meere und Ozeane', 'Ostsee'),
    ('Meere und Ozeane', 'Indischer Ozean'),
    ('Meere und Ozeane', 'Karibik'),
    ('Meere und Ozeane', 'Rotes Meer'),
    ('Meere und Ozeane', 'Schwarzes Meer'),
    ('Meere und Ozeane', 'Arktischer Ozean'),
    ('Meere und Ozeane', 'Ärmelkanal'),
    ('Meere und Ozeane', 'Adriatisches Meer'),
    ('Meere und Ozeane', 'Ägäisches Meer'),
    ('Comic-Helden', 'Spider-Man'),
    ('Comic-Helden', 'Batman'),
    ('Comic-Helden', 'Superman'),
    ('Comic-Helden', 'Iron Man'),
    ('Comic-Helden', 'Hulk'),
    ('Comic-Helden', 'Thor'),
    ('Comic-Helden', 'Captain America'),
    ('Comic-Helden', 'Wonder Woman'),
    ('Comic-Helden', 'Flash'),
    ('Comic-Helden', 'Aquaman'),
    ('Comic-Helden', 'Black Panther'),
    ('Comic-Helden', 'Wolverine'),
    ('Comic-Helden', 'Deadpool'),
    ('Comic-Helden', 'Green Lantern'),
    ('Comic-Helden', 'Doctor Strange'),
    ('Comic-Helden', 'Ant-Man'),
    ('Comic-Helden', 'Black Widow'),
    ('Disney-Filme', 'Frozen'),
    ('Disney-Filme', 'Bambi'),
    ('Disney-Filme', 'Aladdin'),
    ('Disney-Filme', 'Cars'),
    ('Disney-Filme', 'Findet Nemo'),
    ('Disney-Filme', 'Mulan'),
    ('Disney-Filme', 'Moana'),
    ('Disney-Filme', 'Tarzan'),
    ('Disney-Filme', 'Pocahontas'),
    ('Disney-Filme', 'Encanto'),
    ('Disney-Filme', 'Der König der Löwen'),
    ('Disney-Filme', 'Die Schöne und das Biest'),
    ('Disney-Filme', 'Arielle'),
    ('Disney-Filme', 'Toy Story'),
    ('Disney-Filme', 'Cinderella'),
    ('Disney-Filme', 'Dornröschen'),
    ('Disney-Filme', 'Zoomania'),
    ('Videospiele', 'Mario Kart'),
    ('Videospiele', 'FIFA'),
    ('Videospiele', 'Minecraft'),
    ('Videospiele', 'Fortnite'),
    ('Videospiele', 'Tetris'),
    ('Videospiele', 'Pokemon'),
    ('Videospiele', 'GTA'),
    ('Videospiele', 'Zelda'),
    ('Videospiele', 'Call of Duty'),
    ('Videospiele', 'Witcher'),
    ('Videospiele', 'Among Us'),
    ('Videospiele', 'League of Legends'),
    ('Videospiele', 'Counter-Strike'),
    ('Videospiele', 'Valorant'),
    ('Videospiele', 'Overwatch'),
    ('Videospiele', 'Red Dead Redemption'),
    ('Videospiele', 'Cyberpunk 2077'),
    ('Videospiele', 'The Sims'),
    ('Fast-Food-Ketten', 'McDonalds'),
    ('Fast-Food-Ketten', 'Burger King'),
    ('Fast-Food-Ketten', 'KFC'),
    ('Fast-Food-Ketten', 'Subway'),
    ('Fast-Food-Ketten', 'Starbucks'),
    ('Fast-Food-Ketten', 'Pizza Hut'),
    ('Fast-Food-Ketten', 'Domino''s'),
    ('Fast-Food-Ketten', 'Vapiano'),
    ('Fast-Food-Ketten', 'Nordsee'),
    ('Fast-Food-Ketten', 'Five Guys'),
    ('Fast-Food-Ketten', 'Wendy''s'),
    ('Fast-Food-Ketten', 'Taco Bell'),
    ('Fast-Food-Ketten', 'Dunkin Donuts'),
    ('Kleidungsstücke', 'Hose'),
    ('Kleidungsstücke', 'Hemd'),
    ('Kleidungsstücke', 'T-Shirt'),
    ('Kleidungsstücke', 'Jacke'),
    ('Kleidungsstücke', 'Pullover'),
    ('Kleidungsstücke', 'Rock'),
    ('Kleidungsstücke', 'Kleid'),
    ('Kleidungsstücke', 'Socken'),
    ('Kleidungsstücke', 'Shorts'),
    ('Kleidungsstücke', 'Mantel'),
    ('Kleidungsstücke', 'Bluse'),
    ('Kleidungsstücke', 'Weste'),
    ('Kleidungsstücke', 'Schal'),
    ('Kleidungsstücke', 'Handschuhe'),
    ('Kleidungsstücke', 'Mütze'),
    ('Kleidungsstücke', 'Anzug'),
    ('Kleidungsstücke', 'Jeans'),
    ('Kleidungsstücke', 'Leggings'),
    ('Kleidungsstücke', 'Cardigan'),
    ('Schuh-Arten', 'Sneaker'),
    ('Schuh-Arten', 'Stiefel'),
    ('Schuh-Arten', 'Sandalen'),
    ('Schuh-Arten', 'Pumps'),
    ('Schuh-Arten', 'Flip-Flops'),
    ('Schuh-Arten', 'Hausschuhe'),
    ('Schuh-Arten', 'Wanderschuhe'),
    ('Schuh-Arten', 'Ballerinas'),
    ('Schuh-Arten', 'High Heels'),
    ('Schuh-Arten', 'Loafer'),
    ('Schuh-Arten', 'Espadrilles'),
    ('Schuh-Arten', 'Gummistiefel'),
    ('Schuh-Arten', 'Chucks'),
    ('Wetter-Phänomene', 'Regen'),
    ('Wetter-Phänomene', 'Schnee'),
    ('Wetter-Phänomene', 'Hagel'),
    ('Wetter-Phänomene', 'Nebel'),
    ('Wetter-Phänomene', 'Sturm'),
    ('Wetter-Phänomene', 'Gewitter'),
    ('Wetter-Phänomene', 'Sonnenschein'),
    ('Wetter-Phänomene', 'Wind'),
    ('Wetter-Phänomene', 'Tornado'),
    ('Wetter-Phänomene', 'Eis'),
    ('Wetter-Phänomene', 'Orkan'),
    ('Wetter-Phänomene', 'Blitz'),
    ('Wetter-Phänomene', 'Donner'),
    ('Wetter-Phänomene', 'Frost'),
    ('Wetter-Phänomene', 'Tau'),
    ('Wetter-Phänomene', 'Regenbogen'),
    ('Blumen', 'Rose'),
    ('Blumen', 'Tulpe'),
    ('Blumen', 'Sonnenblume'),
    ('Blumen', 'Margerite'),
    ('Blumen', 'Lilie'),
    ('Blumen', 'Veilchen'),
    ('Blumen', 'Nelke'),
    ('Blumen', 'Hyazinthe'),
    ('Blumen', 'Orchidee'),
    ('Blumen', 'Krokus'),
    ('Blumen', 'Narzisse'),
    ('Blumen', 'Gänseblümchen'),
    ('Blumen', 'Mohnblume'),
    ('Blumen', 'Dahlie'),
    ('Blumen', 'Chrysantheme'),
    ('Blumen', 'Lavendel'),
    ('Blumen', 'Iris'),
    ('Blumen', 'Anemone'),
    ('Blumen', 'Löwenzahn'),
    ('Bäume', 'Eiche'),
    ('Bäume', 'Buche'),
    ('Bäume', 'Birke'),
    ('Bäume', 'Kiefer'),
    ('Bäume', 'Tanne'),
    ('Bäume', 'Linde'),
    ('Bäume', 'Ahorn'),
    ('Bäume', 'Kastanie'),
    ('Bäume', 'Esche'),
    ('Bäume', 'Ulme'),
    ('Bäume', 'Fichte'),
    ('Bäume', 'Weide'),
    ('Bäume', 'Pappel'),
    ('Bäume', 'Erle'),
    ('Bäume', 'Lärche'),
    ('Bäume', 'Douglasie'),
    ('Bäume', 'Eibe'),
    ('Bäume', 'Robinie'),
    ('Bäume', 'Walnussbaum'),
    ('Bäume', 'Haselnussbaum'),
    ('Bäume', 'Platane'),
    ('Bäume', 'Zeder'),
    ('Bäume', 'Zypresse'),
    ('Bäume', 'Mammutbaum'),
    ('Bäume', 'Ginkgo'),
    ('Bäume', 'Rotbuche'),
    ('Bäume', 'Hainbuche'),
    ('Bäume', 'Eberesche'),
    ('Bäume', 'Weißdorn'),
    ('Bäume', 'Holunder'),
    ('Bäume', 'Apfelbaum'),
    ('Bäume', 'Birnbaum'),
    ('Bäume', 'Kirschbaum'),
    ('Bäume', 'Pflaumenbaum'),
    ('Bäume', 'Olivenbaum'),
    ('Bäume', 'Zitronenbaum'),
    ('Bäume', 'Mangobaum'),
    ('Bäume', 'Kokospalme'),
    ('Bäume', 'Dattelpalme'),
    ('Bäume', 'Bananenstaude'),
    ('Bäume', 'Bergahorn'),
    ('Bäume', 'Spitzahorn'),
    ('Bäume', 'Flatterulme'),
    ('Bäume', 'Traubeneiche'),
    ('Bäume', 'Stieleiche'),
    ('Bäume', 'Moorbirke'),
    ('Bäume', 'Sandbirke'),
    ('Bäume', 'Trauerweide'),
    ('Bäume', 'Korkeiche'),
    ('Bäume', 'Baobab'),
    ('Fahrzeuge', 'Bus'),
    ('Fahrzeuge', 'Auto'),
    ('Fahrzeuge', 'Fahrrad'),
    ('Fahrzeuge', 'Motorrad'),
    ('Fahrzeuge', 'LKW'),
    ('Fahrzeuge', 'Zug'),
    ('Fahrzeuge', 'U-Bahn'),
    ('Fahrzeuge', 'Straßenbahn'),
    ('Fahrzeuge', 'Flugzeug'),
    ('Fahrzeuge', 'Boot'),
    ('Fahrzeuge', 'Roller'),
    ('Fahrzeuge', 'Traktor'),
    ('Fahrzeuge', 'Wohnmobil'),
    ('Fahrzeuge', 'Taxi'),
    ('Fahrzeuge', 'S-Bahn'),
    ('Fahrzeuge', 'Fähre'),
    ('Fahrzeuge', 'Hubschrauber'),
    ('Fahrzeuge', 'Segelboot'),
    ('Möbelstücke', 'Sofa'),
    ('Möbelstücke', 'Stuhl'),
    ('Möbelstücke', 'Tisch'),
    ('Möbelstücke', 'Bett'),
    ('Möbelstücke', 'Schrank'),
    ('Möbelstücke', 'Regal'),
    ('Möbelstücke', 'Kommode'),
    ('Möbelstücke', 'Sessel'),
    ('Möbelstücke', 'Hocker'),
    ('Möbelstücke', 'Lampe'),
    ('Möbelstücke', 'Couchtisch'),
    ('Möbelstücke', 'Nachttisch'),
    ('Möbelstücke', 'Schreibtisch'),
    ('Möbelstücke', 'Vitrine'),
    ('Möbelstücke', 'Bank'),
    ('Möbelstücke', 'Spiegel'),
    ('Elektrogeräte', 'Toaster'),
    ('Elektrogeräte', 'Mixer'),
    ('Elektrogeräte', 'Wasserkocher'),
    ('Elektrogeräte', 'Föhn'),
    ('Elektrogeräte', 'Staubsauger'),
    ('Elektrogeräte', 'Bügeleisen'),
    ('Elektrogeräte', 'Kaffeemaschine'),
    ('Elektrogeräte', 'Mikrowelle'),
    ('Elektrogeräte', 'Waschmaschine'),
    ('Elektrogeräte', 'Trockner'),
    ('Elektrogeräte', 'Geschirrspüler'),
    ('Elektrogeräte', 'Rasierer'),
    ('Elektrogeräte', 'Ventilator'),
    ('Elektrogeräte', 'Heizlüfter'),
    ('Smartphone-Hersteller', 'Samsung'),
    ('Smartphone-Hersteller', 'Apple'),
    ('Smartphone-Hersteller', 'Huawei'),
    ('Smartphone-Hersteller', 'Xiaomi'),
    ('Smartphone-Hersteller', 'Sony'),
    ('Smartphone-Hersteller', 'LG'),
    ('Smartphone-Hersteller', 'OnePlus'),
    ('Smartphone-Hersteller', 'Google'),
    ('Smartphone-Hersteller', 'Motorola'),
    ('Smartphone-Hersteller', 'Nokia'),
    ('Smartphone-Hersteller', 'Oppo'),
    ('Smartphone-Hersteller', 'Vivo'),
    ('Smartphone-Hersteller', 'Realme'),
    ('Smartphone-Hersteller', 'Honor'),
    ('Soziale Medien', 'Instagram'),
    ('Soziale Medien', 'TikTok'),
    ('Soziale Medien', 'Facebook'),
    ('Soziale Medien', 'Twitter'),
    ('Soziale Medien', 'Snapchat'),
    ('Soziale Medien', 'YouTube'),
    ('Soziale Medien', 'LinkedIn'),
    ('Soziale Medien', 'Pinterest'),
    ('Soziale Medien', 'Reddit'),
    ('Soziale Medien', 'WhatsApp'),
    ('Soziale Medien', 'Telegram'),
    ('Soziale Medien', 'Discord'),
    ('Soziale Medien', 'Twitch'),
    ('Soziale Medien', 'BeReal'),
    ('Bekannte YouTuber', 'MrBeast'),
    ('Bekannte YouTuber', 'PewDiePie'),
    ('Bekannte YouTuber', 'Gronkh'),
    ('Bekannte YouTuber', 'Bibi'),
    ('Bekannte YouTuber', 'Julien Bam'),
    ('Bekannte YouTuber', 'Rezo'),
    ('Bekannte YouTuber', 'Knossi'),
    ('Bekannte YouTuber', 'Trymacs'),
    ('Bekannte YouTuber', 'Inscope21'),
    ('Bekannte YouTuber', 'Unge'),
    ('Bekannte YouTuber', 'Paluten'),
    ('Bekannte YouTuber', 'LeFloid'),
    ('Bekannte YouTuber', 'Ungespielt'),
    ('Bekannte YouTuber', 'Katja Krasavice'),
    ('Bekannte YouTuber', 'Montanablack'),
    ('Kleidungsmarken', 'Nike'),
    ('Kleidungsmarken', 'Adidas'),
    ('Kleidungsmarken', 'Puma'),
    ('Kleidungsmarken', 'H&M'),
    ('Kleidungsmarken', 'Zara'),
    ('Kleidungsmarken', 'Gucci'),
    ('Kleidungsmarken', 'Prada'),
    ('Kleidungsmarken', 'Levis'),
    ('Kleidungsmarken', 'Tommy Hilfiger'),
    ('Kleidungsmarken', 'Hugo Boss'),
    ('Kleidungsmarken', 'Under Armour'),
    ('Kleidungsmarken', 'New Balance'),
    ('Kleidungsmarken', 'Calvin Klein'),
    ('Kleidungsmarken', 'Lacoste'),
    ('Kleidungsmarken', 'Vans'),
    ('Kleidungsmarken', 'Reebok'),
    ('Elektronik-Marken', 'Apple'),
    ('Elektronik-Marken', 'Samsung'),
    ('Elektronik-Marken', 'Sony'),
    ('Elektronik-Marken', 'LG'),
    ('Elektronik-Marken', 'Bose'),
    ('Elektronik-Marken', 'Philips'),
    ('Elektronik-Marken', 'Bosch'),
    ('Elektronik-Marken', 'Siemens'),
    ('Elektronik-Marken', 'Panasonic'),
    ('Elektronik-Marken', 'JBL'),
    ('Elektronik-Marken', 'Sennheiser'),
    ('Elektronik-Marken', 'Canon'),
    ('Elektronik-Marken', 'Nikon'),
    ('Elektronik-Marken', 'Dell'),
    ('Elektronik-Marken', 'HP'),
    ('Elektronik-Marken', 'Lenovo'),
    ('Elektronik-Marken', 'Asus'),
    ('Deutsche Rapper', 'Capital Bra'),
    ('Deutsche Rapper', 'Bushido'),
    ('Deutsche Rapper', 'Sido'),
    ('Deutsche Rapper', 'Kollegah'),
    ('Deutsche Rapper', 'Apache'),
    ('Deutsche Rapper', 'RAF Camora'),
    ('Deutsche Rapper', 'Kontra K'),
    ('Deutsche Rapper', 'Shirin David'),
    ('Deutsche Rapper', 'Cro'),
    ('Deutsche Rapper', 'Fler'),
    ('Deutsche Rapper', 'Farid Bang'),
    ('Deutsche Rapper', 'Samra'),
    ('Deutsche Rapper', 'Luciano'),
    ('Deutsche Rapper', 'Ufo361'),
    ('Deutsche Rapper', 'Bonez MC'),
    ('Deutsche Rapper', 'Gzuz'),
    ('Deutsche Rapper', '01099'),
    ('Deutsche Rapper', 'Rin'),
    ('Kinderspiele', 'Verstecken'),
    ('Kinderspiele', 'Fangen'),
    ('Kinderspiele', 'Mensch ärgere dich nicht'),
    ('Kinderspiele', 'UNO'),
    ('Kinderspiele', 'Memory'),
    ('Kinderspiele', 'Stadt Land Fluss'),
    ('Kinderspiele', 'Twister'),
    ('Kinderspiele', 'Mau Mau'),
    ('Kinderspiele', 'Blinde Kuh'),
    ('Kinderspiele', 'Himmel und Hölle'),
    ('Kinderspiele', 'Gummitwist'),
    ('Kinderspiele', 'Seilspringen'),
    ('Brettspiele', 'Monopoly'),
    ('Brettspiele', 'Risiko'),
    ('Brettspiele', 'Catan'),
    ('Brettspiele', 'Scrabble'),
    ('Brettspiele', 'Backgammon'),
    ('Brettspiele', 'Dame'),
    ('Brettspiele', 'Schach'),
    ('Brettspiele', 'Trivial Pursuit'),
    ('Brettspiele', 'Cluedo'),
    ('Brettspiele', 'Mensch ärgere dich nicht'),
    ('Brettspiele', 'Uno'),
    ('Brettspiele', 'Rummikub'),
    ('Brettspiele', 'Carcassonne'),
    ('Brettspiele', 'Dixit'),
    ('Handwerks-Berufe', 'Tischler'),
    ('Handwerks-Berufe', 'Schreiner'),
    ('Handwerks-Berufe', 'Maurer'),
    ('Handwerks-Berufe', 'Elektriker'),
    ('Handwerks-Berufe', 'Klempner'),
    ('Handwerks-Berufe', 'Maler'),
    ('Handwerks-Berufe', 'Schlosser'),
    ('Handwerks-Berufe', 'Dachdecker'),
    ('Handwerks-Berufe', 'Friseur'),
    ('Handwerks-Berufe', 'Zimmermann'),
    ('Handwerks-Berufe', 'Installateur'),
    ('Handwerks-Berufe', 'Fliesenleger'),
    ('Handwerks-Berufe', 'Gärtner'),
    ('Handwerks-Berufe', 'Schweißer'),
    ('Deutschrap-Songs', 'Tequila'),
    ('Deutschrap-Songs', 'Wolke 10'),
    ('Deutschrap-Songs', 'Puuh Bär'),
    ('Deutschrap-Songs', 'Rockstar'),
    ('Deutschrap-Songs', 'Athen'),
    ('Deutschrap-Songs', 'Neymar'),
    ('Deutschrap-Songs', 'Millionär'),
    ('Deutschrap-Songs', 'Blaulicht'),
    ('Deutschrap-Songs', 'Vermissen'),
    ('Deutschrap-Songs', 'Dior'),
    ('Deutschrap-Songs', 'Bonez MC'),
    ('Deutschrap-Songs', 'Gangsta Rap'),
    ('Deutschrap-Songs', 'Willst du'),
    ('Deutschrap-Songs', 'Anfang'),
    ('Deutschrap-Songs', 'Powergirl'),
    ('Deutschrap-Songs', 'Meine Soldaten'),
    ('Deutschrap-Songs', 'Roller'),
    ('Deutschrap-Songs', 'Blackout'),
    ('Deutschrap-Songs', 'Palmen aus Plastik'),
    ('Deutschrap-Songs', 'Nicht verdient'),
    ('Deutschrap-Songs', '3 Millionen'),
    ('Deutschrap-Songs', 'Nightliner'),
    ('Deutschrap-Songs', 'Nur noch Gangster'),
    ('Deutschrap-Songs', 'Nummer 1'),
    ('Deutschrap-Songs', 'Nicht so wichtig'),
    ('Deutschrap-Songs', 'Nur für dich'),
    ('Deutschrap Klassiker', 'Halt dich fest'),
    ('Deutschrap Klassiker', 'Wilma rennt'),
    ('Deutschrap Klassiker', 'Für immer jung'),
    ('Deutschrap Klassiker', '1000 PS'),
    ('Deutschrap Klassiker', 'Wer hat Angst vorm schwarzen Mann'),
    ('Deutschrap Klassiker', 'Wo ist das Geld'),
    ('Deutschrap Klassiker', 'Berlin lebt'),
    ('Deutschrap Klassiker', 'Alles auf Rot'),
    ('Deutschrap Klassiker', 'Bilder im Kopf'),
    ('Deutschrap Klassiker', 'Frei sein'),
    ('Deutschrap Klassiker', 'Phantom'),
    ('Deutschrap Klassiker', 'Adrenalin'),
    ('Deutschrap Klassiker', 'Vermissen'),
    ('Deutschrap Klassiker', 'Prinzessin'),
    ('Deutschrap Klassiker', 'Willkommen im Bundestag'),
    ('Deutschrap Klassiker', 'Aggro Ansage Nr.1'),
    ('Deutschrap Klassiker', 'Bild dir deine Meinung'),
    ('Deutschrap Klassiker', 'Denkmal'),
    ('Deutschrap Klassiker', 'Wilder Wilder Westen'),
    ('Deutschrap Klassiker', 'Party Prinzessin'),
    ('Englische All-Time-Hits', 'Bohemian Rhapsody'),
    ('Englische All-Time-Hits', 'Billie Jean'),
    ('Englische All-Time-Hits', 'Rolling in the Deep'),
    ('Englische All-Time-Hits', 'Shape of You'),
    ('Englische All-Time-Hits', 'Blinding Lights'),
    ('Englische All-Time-Hits', 'Someone Like You'),
    ('Englische All-Time-Hits', 'Sweet Child O'' Mine'),
    ('Englische All-Time-Hits', 'Smells Like Teen Spirit'),
    ('Englische All-Time-Hits', 'Hotel California'),
    ('Englische All-Time-Hits', 'I Want It That Way'),
    ('Englische All-Time-Hits', 'Uptown Funk'),
    ('Englische All-Time-Hits', 'Umbrella'),
    ('Englische All-Time-Hits', 'Poker Face'),
    ('Englische All-Time-Hits', 'Firework'),
    ('Englische All-Time-Hits', 'Radioactive'),
    ('Englische All-Time-Hits', 'Thinking Out Loud'),
    ('Englische All-Time-Hits', 'Shake It Off'),
    ('Englische All-Time-Hits', 'Stayin'' Alive'),
    ('Englische All-Time-Hits', 'Like a Prayer'),
    ('Englische All-Time-Hits', 'Wonderwall'),
    ('Internationale Pop-Charts', 'Espresso'),
    ('Internationale Pop-Charts', 'Flowers'),
    ('Internationale Pop-Charts', 'As It Was'),
    ('Internationale Pop-Charts', 'Anti-Hero'),
    ('Internationale Pop-Charts', 'Cruel Summer'),
    ('Internationale Pop-Charts', 'Levitating'),
    ('Internationale Pop-Charts', 'Peaches'),
    ('Internationale Pop-Charts', 'Watermelon Sugar'),
    ('Internationale Pop-Charts', 'Good 4 U'),
    ('Internationale Pop-Charts', 'Stay'),
    ('Internationale Pop-Charts', 'Circles'),
    ('Internationale Pop-Charts', 'Blinding Lights'),
    ('Internationale Pop-Charts', 'Kill Bill'),
    ('Internationale Pop-Charts', 'Vampire'),
    ('Internationale Pop-Charts', 'Greedy'),
    ('Internationale Pop-Charts', 'Lose Control'),
    ('Internationale Pop-Charts', 'Die With a Smile'),
    ('Internationale Pop-Charts', 'Birds of a Feather'),
    ('Internationale Pop-Charts', 'Houdini')
) AS v(topic, answer) ON lower(tp.text) = lower(v.topic)
ON CONFLICT (topic_pool_id, lower_answer) DO NOTHING;
COMMIT;
